org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=tntsulfurcubes
mod.name=TNT Sulfur Cubes
mod.group=net.mat0u5
mod.version=1.2.0
mod.version_prefix=
mod.version_suffix=
mod.authors=Mat0u5
mod.contributors=
mod.license=MIT
mod.description=Exploding sulfur cubes with TNT!
mod.sources_url=https://github.com/Mat0u5/TNTSulfurCubes
mod.homepage_url=https://github.com/Mat0u5/TNTSulfurCubes
mod.issues_url=https://github.com/Mat0u5/TNTSulfurCubes/issues
mod.discord_url=https://discord.gg/QWJxfb4zQZ

deps.minecraft=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.forge=[VERSIONED]

# Publishing
publish.dryrun=false

publish.modrinth.id=mM6ImTKb
publish.curseforge.id=1507575

publish.modrinth=true
publish.curseforge=true
publish.github=true
publish.discord=false

publish.release.fabric=stable
publish.release.neoforge=stable
publish.release.forge=stable

publish.github.prerelease=false
publish.discord.dev=false

publish.github.branch=main
publish.github.target=Mat0u5/TNTSulfurCubes
